Moo expects subroutine reference for complex data
Alter StatusListener to fix following error:
Invalid default 'IntelliHome::Interfaces::Terminal=HASH(0x195c800)' for
IntelliHome::Workers::Master::StatusListener->Output not a coderef or a
non-ref and could not be converted to a coderef: Not a subroutine
reference at /usr/local/share/perl/5.18.2/Method/Generate/Accessor.pm
line 660.
Compilation failed in require at -e line 1.
BEGIN failed--compilation aborted at -e line 1.